テストの結果の変数はsut(System Under Test)とする。

## 例外の確認


@Test
public void 異常系_キー無し() {
    assertThatThrownBy(() -> {
        IS3GetRepository s3 = new S3Get();
        s3.GetBytes("kero20220320a", "sample2.txt");
    }).isInstanceOfSatisfying(MyS3Exception.class, e -> {
        assertThat(e.getMessage()).isEqualTo("key:[sample2.txt]が見つかりませんでした。");
    });
}

## 戻り値のあるpublicメソッドの挙動を変更

Entity entity = mock(Entity.class);

Mockito.when(モックインスタンス.メソッド(任意の引数)).thenReturn(任意の戻り値);

## Mockが呼ばれたか確認する

ArgumentCaptorを使う。以下を参照。
https://qiita.com/kyabetsuda/items/16c565460580a8354f6a